const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=c=>(Number(c||0)/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export function renderFinance(root,payload,media,api,refresh){
 const rows=payload?.advertisers??[], companies=payload?.companies??[], totals=payload?.totals??{amountCents:payload?.totalAmountCents||0,displays:payload?.totalDisplays||0};
 const companyOptions=companies.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');
 root.innerHTML=`<header class="page-head"><div><p class="eyebrow">Comercial sem cobrança automática</p><h1>Empresas & resultados</h1><p>Cadastre clientes, vincule mídias, informe a mensalidade recebida e comprove cada exibição.</p></div><button class="ghost" onclick="window.print()">Exportar / imprimir</button></header>
 <section class="kpi-grid"><article><span>Mensalidades</span><strong>${money(totals.amountCents)}</strong><small>valor informado</small></article><article><span>Exibições</span><strong>${totals.displays||0}</strong><small>reproduções concluídas</small></article><article><span>Empresas</span><strong>${rows.length}</strong><small>no relatório</small></article><article><span>Custo médio</span><strong>${totals.displays?money(Math.round(totals.amountCents/totals.displays)):'—'}</strong><small>por exibição</small></article></section>
 <section class="finance-layout"><form class="glass editor" data-company><h2>Cadastrar empresa</h2><label>Nome<input name="name" required></label><label>Contato<input name="contactName"></label><label>Telefone<input name="phone"></label><label>E-mail<input name="email" type="email"></label><label>Observações<input name="notes"></label><button class="primary">Salvar empresa</button><p role="status"></p></form>
 <article class="glass chart-card"><h2>Exibições por empresa</h2><div class="bar-chart" data-chart="displays">${rows.map(r=>`<div><span>${esc(r.advertiser_name||r.name)}</span><i style="--value:${Math.max(3,Math.min(100,(r.displays||0)*5))}%"></i><b>${r.displays||0}</b></div>`).join('')||'<p>Os gráficos aparecem após as primeiras exibições.</p>'}</div></article></section>
 <section class="finance-layout"><form class="glass editor" data-month><h2>Registrar mensalidade</h2><label>Empresa<select name="advertiserId" required><option value="">Selecione</option>${companyOptions}</select></label><label>Competência<input name="competence" type="month" value="${payload?.competence||new Date().toISOString().slice(0,7)}" required></label><label>Valor recebido (R$)<input name="monthlyAmount" type="number" min="0" step="0.01" required></label><label>Situação<select name="status"><option value="paid">Pago</option><option value="pending">Pendente</option><option value="late">Atrasado</option><option value="courtesy">Cortesia</option></select></label><label>Observações<input name="notes"></label><button class="primary">Salvar mensalidade</button><p role="status"></p></form>
 <form class="glass editor" data-media-links><h2>Vincular mídias à empresa</h2><label>Empresa<select name="advertiserId" required><option value="">Selecione</option>${companyOptions}</select></label><div class="media-checklist">${media.map(m=>`<label><input type="checkbox" name="assetIds" value="${m.id}"> ${esc(m.display_name||m.original_name)} <small>${esc(m.content_type)}</small></label>`).join('')||'<p>Suba mídias na Biblioteca para vinculá-las.</p>'}</div><button class="primary">Salvar vínculos</button><p role="status"></p></form></section>
 <section class="glass report"><table><thead><tr><th>Empresa</th><th>Mensalidade</th><th>Status</th><th>Exibições</th><th>TVs</th><th>Custo por exibição</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.advertiser_name||r.name)}</td><td>${money(r.monthlyAmountCents??r.monthly_amount_cents)}</td><td>${esc(r.payment_status||'pendente')}</td><td>${r.displays||0}</td><td>${r.tvs||0}</td><td>${r.costPerDisplayCents==null&&r.cost_per_display_cents==null?'—':money(r.costPerDisplayCents??r.cost_per_display_cents)}</td></tr>`).join('')||'<tr><td colspan="6">Cadastre uma empresa para começar.</td></tr>'}</tbody></table></section>`;
 root.querySelector('[data-company]')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,s=f.querySelector('[role=status]');try{await api('/admin/advertisers',{method:'POST',body:Object.fromEntries(new FormData(f))});s.textContent='Empresa cadastrada.';await refresh();}catch(x){s.textContent=`Falha: ${x.message}`;}});
 root.querySelector('[data-month]')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,s=f.querySelector('[role=status]'),v=Object.fromEntries(new FormData(f)),id=v.advertiserId;delete v.advertiserId;try{await api(`/admin/advertisers/${id}/months`,{method:'POST',body:v});s.textContent='Mensalidade registrada.';await refresh();}catch(x){s.textContent=`Falha: ${x.message}`;}});
 root.querySelector('[data-media-links]')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,s=f.querySelector('[role=status]'),fd=new FormData(f),id=fd.get('advertiserId'),assetIds=fd.getAll('assetIds');try{await api(`/admin/advertisers/${id}/media`,{method:'PUT',body:{assetIds}});s.textContent='Mídias vinculadas.';await refresh();}catch(x){s.textContent=`Falha: ${x.message}`;}});
}
