const esc = (value) => String(value ?? '').replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));
const list = (value, key) => Array.isArray(value) ? value : Array.isArray(value?.[key]) ? value[key] : [];

export function renderLibrary(root, payload, apiClient, refresh) {
  const media = list(payload, 'media');
  root.innerHTML = `<header class="page-head"><div><p class="eyebrow">Conteúdo central</p><h1>Biblioteca</h1><p>Envie imagens e vídeos uma vez e use em várias playlists.</p></div><span class="pill">${media.length} mídias</span></header>
  <section class="glass upload-card"><form data-upload><label class="dropzone">Adicionar mídia<input name="media" type="file" accept="image/jpeg,image/png,image/webp,video/mp4" required></label><label>Nome<input name="displayName" required maxlength="120"></label><label>Duração da imagem (segundos)<input name="durationSeconds" type="number" min="1" max="3600" value="10"></label><button class="primary">Enviar para a biblioteca</button><p role="status"></p></form></section>
  <div class="library-tools"><input data-media-search type="search" placeholder="Buscar mídia"><select data-media-type><option value="all">Todos os tipos</option><option value="image">Imagens</option><option value="video">Vídeos</option></select><button type="button" class="ghost" data-view-mode>Grade / lista</button></div><section class="media-grid" data-media-grid>${media.map(renderMediaCard).join('') || '<div class="empty">Sua biblioteca ainda está vazia.</div>'}</section>`;
  root.querySelector('[data-upload]').addEventListener('submit', async (event) => {
    event.preventDefault(); const form = event.currentTarget; const data = new FormData(); const file = form.querySelector('[name="media"]').files[0];
    data.set('media', file); data.set('name', form.querySelector('[name="displayName"]').value); if (file.type.startsWith('image/')) data.set('durationSeconds', form.querySelector('[name="durationSeconds"]').value);
    const status = form.querySelector('[role=status]'); status.textContent = 'Enviando…';
    try { await apiClient('/admin/media', { method: 'POST', body: data }); status.textContent = 'Mídia enviada com sucesso.'; playUiSound('success'); await refresh(); } catch (error) { status.textContent = `Não foi possível enviar a mídia (${error.message}).`; playUiSound('error'); }
  });
  const updateGrid = () => { const filtered = filterMedia(media, { query: root.querySelector('[data-media-search]').value, type: root.querySelector('[data-media-type]').value }); root.querySelector('[data-media-grid]').innerHTML = filtered.map(renderMediaCard).join('') || '<div class="empty">Nenhuma mídia encontrada.</div>'; bindEditors(); };
  const bindEditors = () => root.querySelectorAll('[data-edit-media]').forEach((button) => button.addEventListener('click', async () => { const detail = await apiClient(`/admin/media/${button.dataset.editMedia}`); openMediaEditor(root, detail, apiClient); }));
  root.querySelector('[data-media-search]').addEventListener('input', updateGrid); root.querySelector('[data-media-type]').addEventListener('change', updateGrid); root.querySelector('[data-view-mode]').addEventListener('click', () => root.querySelector('[data-media-grid]').classList.toggle('media-list')); bindEditors();
}

export function renderPlaylists(root, playlistPayload, mediaPayload, apiClient, refresh) {
  const playlists = list(playlistPayload, 'playlists'); const media = list(mediaPayload, 'media');
  root.innerHTML = `<header class="page-head"><div><p class="eyebrow">Ordem de exibição</p><h1>Playlists</h1><p>Organize exatamente a sequência que as TVs devem reproduzir.</p></div><span class="pill">${playlists.length} listas</span></header>
  <section class="split"><form class="glass editor" data-playlist><h2>Nova playlist</h2><label>Nome<input name="name" required></label><div class="asset-picker">${media.map((m, i) => `<label><input type="checkbox" name="asset" value="${m.id}" data-type="${m.content_type}" data-duration="${m.duration_seconds || 10}"><span>${i + 1}</span>${esc(m.display_name)}</label>`).join('') || '<p>Envie mídias na Biblioteca primeiro.</p>'}</div><button class="primary">Salvar playlist</button><p role="status"></p></form>
  <div class="stack">${playlists.map((p) => `<article class="glass list-card"><span>${p.item_count || 0} itens</span><h3>${esc(p.name)}</h3><p>${esc(p.status || 'active')}</p></article>`).join('') || '<div class="empty">Nenhuma playlist criada.</div>'}</div></section>`;
  root.querySelector('[data-playlist]').addEventListener('submit', async (event) => { event.preventDefault(); const form = event.currentTarget; const selected = [...form.querySelectorAll('[name=asset]:checked')]; const items = selected.map((node, position) => ({ assetId: node.value, position, imageDurationSeconds: node.dataset.type.startsWith('image/') ? Number(node.dataset.duration) : null })); const status = form.querySelector('[role=status]'); try { await apiClient('/admin/playlists', { method: 'POST', body: { name: form.name.value.trim(), items } }); status.textContent = 'Playlist salva.'; playUiSound('success'); await refresh(); } catch { status.textContent = 'Revise o nome e selecione pelo menos uma mídia.'; playUiSound('alert'); } });
}

export function renderSchedule(root, data, apiClient, refresh) {
  const playlists = list(data.playlists, 'playlists'); const devices = list(data.devices, 'devices'); const schedules = list(data.schedules, 'schedules');
  root.innerHTML = `<header class="page-head"><div><p class="eyebrow">Quem · onde · quando</p><h1>Programação</h1><p>Defina a playlist, o destino, o período e a prioridade.</p></div></header><section class="split"><form class="glass editor" data-schedule><label>Playlist<select name="playlistId" required><option value="">Escolha…</option>${playlists.map((p) => `<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><label>Destino<select name="target"><option value="all">Todas as TVs</option>${devices.map((d) => `<option value="${d.id}">${esc(d.name)}</option>`).join('')}</select></label><div class="field-row"><label>Início<input name="startsAt" type="datetime-local" required></label><label>Fim<input name="endsAt" type="datetime-local" required></label></div><label>Prioridade<select name="priority"><option value="normal">Normal</option><option value="alta">Alta</option><option value="urgente">Urgente</option></select></label><button class="primary">Publicar programação</button><p role="status"></p></form><div class="stack">${schedules.map((s) => `<article class="glass list-card"><span class="priority p-${s.priority}">${s.priority >= 100 ? 'Urgente' : s.priority >= 50 ? 'Alta' : 'Normal'}</span><h3>${esc(s.playlist_name || 'Campanha')}</h3><p>${esc(s.target_name)} · ${new Date(s.starts_at).toLocaleString('pt-BR')}</p></article>`).join('') || '<div class="empty">Nenhuma programação publicada.</div>'}</div></section>`;
  root.querySelector('[data-schedule]').addEventListener('submit', async (event) => { event.preventDefault(); const f=event.currentTarget; const target=f.target.value; try { await apiClient('/admin/schedules',{method:'POST',body:{playlistId:f.playlistId.value,target:{type:target==='all'?'all':'device',id:target==='all'?null:target},startsAt:new Date(f.startsAt.value).toISOString(),endsAt:new Date(f.endsAt.value).toISOString(),priority:f.priority.value}}); f.querySelector('[role=status]').textContent='Programação enviada às TVs.'; playUiSound('success'); await refresh(); } catch { f.querySelector('[role=status]').textContent='Não foi possível publicar. Revise os campos.'; playUiSound('error'); } });
}

export function renderLive(root, payload) { const devices=list(payload,'devices'); root.innerHTML=`<header class="page-head"><div><p class="eyebrow">Operação em tempo real</p><h1>Ao vivo</h1><p>O que toca agora, próximo download, armazenamento e falhas.</p></div><span class="live-dot">atualização 30 s</span></header><section class="live-grid">${devices.map(d=>`<article class="glass live-card"><div><i class="${d.online?'on':'off'}"></i><h3>${esc(d.name)}</h3></div><dl><dt>Agora</dt><dd>${esc(d.current_media_name||'Sem reprodução')}</dd><dt>Próximo</dt><dd>${esc(d.next_media_name||'Aguardando')}</dd><dt>Download</dt><dd>${esc(d.download_status||'—')}</dd><dt>Armazenamento</dt><dd>${d.storage_free_bytes?`${Math.round(d.storage_free_bytes/1073741824*10)/10} GB livres`:'—'}</dd></dl></article>`).join('')||'<div class="empty">Nenhuma TV enviou telemetria ainda.</div>'}</section>`; }
export function renderReports(root,payload){const events=list(payload,'events');root.innerHTML=`<header class="page-head"><div><p class="eyebrow">Comprovação</p><h1>Relatórios</h1><p>Histórico de reproduções, downloads e erros por TV e mídia.</p></div><button class="ghost" onclick="window.print()">Exportar / imprimir</button></header><section class="glass report"><table><thead><tr><th>Quando</th><th>TV</th><th>Mídia</th><th>Evento</th></tr></thead><tbody>${events.map(e=>`<tr><td>${new Date(e.occurred_at).toLocaleString('pt-BR')}</td><td>${esc(e.device_name)}</td><td>${esc(e.media_name||'—')}</td><td>${esc(e.event_type)}</td></tr>`).join('')||'<tr><td colspan="4">Nenhum evento registrado.</td></tr>'}</tbody></table></section>`;}
import { filterMedia, renderMediaCard } from './library.js';
import { openMediaEditor } from './media-editor.js';
import { playUiSound } from './sound.js';
