window.NEWS_DATA = [
  {
    "id": "https://ac24horas.com/2026/04/15/no-acre-kit-camera-de-seguranca-e-o-item-mais-vendido-na-shopee/",
    "slug": "no-acre-kit-camera-de-seguranca-e-o-item-mais-vendido-na-shopee",
    "title": "No Acre, kit câmera de segurança é o item mais vendido na Shopee",
    "summary": "O comportamento de consumo digital no Acre tem se voltado cada vez mais para a segurança doméstica. Dados do levantamento “Mapa Shopee 2026”, da Shopee, divulgado nesta quarta-feira, 15, mostram que o item mais vendido no estado, acima da média nacional, é o kit de câmera de segurança. No recorte regional, o Norte apresenta um [&#8230;]",
    "lede": "O comportamento de consumo digital no Acre tem se voltado cada vez mais para a segurança doméstica. Dados do levantamento “Mapa Shopee 2026”, da Shopee, divulgado nesta quarta-feira, 15, mostram que o item mais vendido no estado, acima da média nacional, é o kit de câmera de segurança. No recorte regional, o Norte apresenta um [&#8230;]",
    "url": "https://ac24horas.com/2026/04/15/no-acre-kit-camera-de-seguranca-e-o-item-mais-vendido-na-shopee/",
    "sourceUrl": "https://ac24horas.com/2026/04/15/no-acre-kit-camera-de-seguranca-e-o-item-mais-vendido-na-shopee/",
    "sourceName": "ac24horas",
    "sourceLabel": "No Acre, kit câmera de segurança é o item mais vendido na Shopee",
    "category": "Negócios",
    "publishedAt": "2026-04-16T02:54:11.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T215242.694.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T215242.694.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/671814928_18578354452049044_673678406970478725_n-1-960x1200.jpg"
  },
  {
    "id": "https://ac24horas.com/2026/04/15/acre-ocupa-16a-posicao-em-ranking-nacional-de-bolsas-de-mestrado-e-doutorado/",
    "slug": "acre-ocupa-16-posicao-no-ranking-de-bolsas-de-mestrado-e-doutorado",
    "title": "Acre ocupa 16ª posição no ranking de bolsas de mestrado e doutorado",
    "summary": "O Acre aparece na 16ª posição no ranking nacional que mede a proporção de bolsas de mestrado e doutorado entre os estados, segundo levantamento do Centro de Liderança Pública no Ranking de Competitividade dos Estados 2025. Os dados foram divulgados na quarta-feira (15). O indicador avalia o percentual de estudantes de pós-graduação beneficiados por bolsas [&#8230;]",
    "lede": "O Acre aparece na 16ª posição no ranking nacional que mede a proporção de bolsas de mestrado e doutorado entre os estados, segundo levantamento do Centro de Liderança Pública no Ranking de Competitividade dos Estados 2025. Os dados foram divulgados na quarta-feira (15). O indicador avalia o percentual de estudantes de pós-graduação beneficiados por bolsas [&#8230;]",
    "url": "https://ac24horas.com/2026/04/15/acre-ocupa-16a-posicao-em-ranking-nacional-de-bolsas-de-mestrado-e-doutorado/",
    "sourceUrl": "https://ac24horas.com/2026/04/15/acre-ocupa-16a-posicao-em-ranking-nacional-de-bolsas-de-mestrado-e-doutorado/",
    "sourceName": "ac24horas",
    "sourceLabel": "Acre ocupa 16ª posição no ranking de bolsas de mestrado e doutorado",
    "category": "Negócios",
    "publishedAt": "2026-04-16T02:30:23.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/2019-01-22-Mestrado-e-doutorado.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/2019-01-22-Mestrado-e-doutorado.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/670423744_18416257303181055_5686848817501534085_n-901x1200.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/15/beneficiarios-do-inss-no-acre-ja-podem-consultar-valor-do-13o-antecipado/",
    "slug": "beneficiarios-do-inss-no-acre-ja-podem-consultar-valor-do-13-antecipado",
    "title": "Beneficiários do INSS no Acre já podem consultar valor do 13º antecipado",
    "summary": "Foto: Reprodução/ Internet \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/d4a1176e-7273-4b39-a06e-114b6729164c-300x200.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/d4a1176e-7273-4b39-a06e-114b6729164c.jpg\" Os beneficiários do Acre já podem consultar a prévia do 13º salário antecipado por meio do aplicativo e site Meu INSS. A medida foi liberada pelo Instituto Nacional do Seguro Social e permite que segurados verifiquem os valores diretamente no extrato de pagamento. No estado, 80.305 beneficiários serão contemplados, com um total estimado de R$ [&#8230;]",
    "lede": "Foto: Reprodução/ Internet \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/d4a1176e-7273-4b39-a06e-114b6729164c-300x200.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/d4a1176e-7273-4b39-a06e-114b6729164c.jpg\" Os beneficiários do Acre já podem consultar a prévia do 13º salário antecipado por meio do aplicativo e site Meu INSS. A medida foi liberada pelo Instituto Nacional do Seguro Social e permite que segurados verifiquem os valores diretamente no extrato de pagamento. No estado, 80.305 beneficiários serão contemplados, com um total estimado de R$ [&#8230;]",
    "url": "https://ac24horas.com/2026/04/15/beneficiarios-do-inss-no-acre-ja-podem-consultar-valor-do-13o-antecipado/",
    "sourceUrl": "https://ac24horas.com/2026/04/15/beneficiarios-do-inss-no-acre-ja-podem-consultar-valor-do-13o-antecipado/",
    "sourceName": "ac24horas",
    "sourceLabel": "Beneficiários do INSS no Acre já podem consultar valor do 13º antecipado",
    "category": "Utilidade Pública",
    "publishedAt": "2026-04-16T02:24:37.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/d4a1176e-7273-4b39-a06e-114b6729164c.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/d4a1176e-7273-4b39-a06e-114b6729164c.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-15-at-16.58.34-1200x765.jpeg"
  },
  {
    "id": "https://ac24horas.com/2026/04/15/galvez-goleia-o-monte-roraima-e-vence-a-1a-na-copa-norte/",
    "slug": "galvez-goleia-o-monte-roraima-e-vence-a-1-na-copa-norte",
    "title": "Galvez goleia o Monte Roraima e vence a 1ª na Copa Norte",
    "summary": "Foto: Sueli Rodrigues -Eduardo fez uma boa partida pelo Imperador \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T211153.347-300x214.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T211153.347.jpg\" O Galvez goleou o Monte Roraima, de Roraima, por 6 a 3 nesta quarta, 15, no Tonicão, e conquistou a primeira vitória na Copa Norte. Eduardo(2), Daniego(2) e Luquinhas(2) marcaram os gols do Imperador enquanto Jean Moraes, Lucas e Davi anotaram para o Tamanduá. Galvez eliminado Mesmo com a goleada diante do Monte Roraima, o [&#8230;]",
    "lede": "Foto: Sueli Rodrigues -Eduardo fez uma boa partida pelo Imperador \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T211153.347-300x214.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T211153.347.jpg\" O Galvez goleou o Monte Roraima, de Roraima, por 6 a 3 nesta quarta, 15, no Tonicão, e conquistou a primeira vitória na Copa Norte. Eduardo(2), Daniego(2) e Luquinhas(2) marcaram os gols do Imperador enquanto Jean Moraes, Lucas e Davi anotaram para o Tamanduá. Galvez eliminado Mesmo com a goleada diante do Monte Roraima, o [&#8230;]",
    "url": "https://ac24horas.com/2026/04/15/galvez-goleia-o-monte-roraima-e-vence-a-1a-na-copa-norte/",
    "sourceUrl": "https://ac24horas.com/2026/04/15/galvez-goleia-o-monte-roraima-e-vence-a-1a-na-copa-norte/",
    "sourceName": "ac24horas",
    "sourceLabel": "Galvez goleia o Monte Roraima e vence a 1ª na Copa Norte",
    "category": "Esporte",
    "publishedAt": "2026-04-16T02:20:56.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T211153.347.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T211153.347.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-14-16-51-43-1200x801.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/15/joelma-tambem-e-cogitada-para-festa-do-trabalhador-no-acre/",
    "slug": "joelma-tambem-e-cogitada-para-festa-do-trabalhador-no-acre",
    "title": "Joelma também é cogitada para Festa do Trabalhador no Acre",
    "summary": "Foto: Reprodução/Instagram \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T203559.779-300x214.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T203559.779.jpg\" A cantora Joelma está sendo sondada para fazer show no Acre na Festa do Trabalhador, em 1º de maio. O governo do Estado fará shows em Rio Branco e Cruzeiro do Sul e a paraense poderá subir ao palco de uma das duas cidades. O nome da banda Calcinha Preta também já foi citado pelos [&#8230;]",
    "lede": "Foto: Reprodução/Instagram \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T203559.779-300x214.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T203559.779.jpg\" A cantora Joelma está sendo sondada para fazer show no Acre na Festa do Trabalhador, em 1º de maio. O governo do Estado fará shows em Rio Branco e Cruzeiro do Sul e a paraense poderá subir ao palco de uma das duas cidades. O nome da banda Calcinha Preta também já foi citado pelos [&#8230;]",
    "url": "https://ac24horas.com/2026/04/15/joelma-tambem-e-cogitada-para-festa-do-trabalhador-no-acre/",
    "sourceUrl": "https://ac24horas.com/2026/04/15/joelma-tambem-e-cogitada-para-festa-do-trabalhador-no-acre/",
    "sourceName": "ac24horas",
    "sourceLabel": "Joelma também é cogitada para Festa do Trabalhador no Acre",
    "category": "Prefeitura",
    "publishedAt": "2026-04-16T01:37:24.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T203559.779.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T203559.779.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2025-05-01-at-02.01.35-4-1200x800.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/15/libertadores-cruzeiro-tropeca-e-perde-para-a-universidad-catolica-em-casa/",
    "slug": "libertadores-cruzeiro-tropeca-e-perde-para-a-universidad-catolica-em-casa",
    "title": "Libertadores: Cruzeiro tropeça e perde para a Universidad Católica em casa",
    "summary": "Justo Giani comemora o primeiro gol da Universidad Católica sobre o Cruzeiro no Mineirão • Reprodução/X @Cruzados \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/gol-universidad-catolica-cruzeiro-300x169.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/gol-universidad-catolica-cruzeiro.webp\" Os mais de 40 mil torcedores do Cruzeiro que foram ao Mineirão, nesta quarta-feira (15), viram uma derrota dolorosa por 2 a 1 para a Universidad Católica pela segunda rodada do grupo D da Libertadores. O gol do triunfo chileno saiu aos 48 minutos do segundo tempo, quando a Raposa não conseguia emplacar uma pressão [&#8230;]",
    "lede": "Justo Giani comemora o primeiro gol da Universidad Católica sobre o Cruzeiro no Mineirão • Reprodução/X @Cruzados \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/gol-universidad-catolica-cruzeiro-300x169.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/gol-universidad-catolica-cruzeiro.webp\" Os mais de 40 mil torcedores do Cruzeiro que foram ao Mineirão, nesta quarta-feira (15), viram uma derrota dolorosa por 2 a 1 para a Universidad Católica pela segunda rodada do grupo D da Libertadores. O gol do triunfo chileno saiu aos 48 minutos do segundo tempo, quando a Raposa não conseguia emplacar uma pressão [&#8230;]",
    "url": "https://ac24horas.com/2026/04/15/libertadores-cruzeiro-tropeca-e-perde-para-a-universidad-catolica-em-casa/",
    "sourceUrl": "https://ac24horas.com/2026/04/15/libertadores-cruzeiro-tropeca-e-perde-para-a-universidad-catolica-em-casa/",
    "sourceName": "ac24horas",
    "sourceLabel": "Libertadores: Cruzeiro tropeça e perde para a Universidad Católica em casa",
    "category": "Esporte",
    "publishedAt": "2026-04-16T01:28:37.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/gol-universidad-catolica-cruzeiro.webp",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/gol-universidad-catolica-cruzeiro.webp",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/55210501855_9ca6af6e9f_o-1200x800.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/15/danilo-decide-no-fim-e-botafogo-vence-o-racing-na-sul-americana/",
    "slug": "danilo-decide-no-fim-e-botafogo-vence-o-racing-na-sul-americana",
    "title": "Danilo decide no fim, e Botafogo vence o Racing na Sul-Americana",
    "summary": "Jogadores do Botafogo celebram gol de Júnior Santos • Vitor Silva/Botafogo \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/55210501855_9ca6af6e9f_o-300x200.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/55210501855_9ca6af6e9f_o-1200x800.webp\" O Botafogo conquistou uma importante vitória fora de casa ao derrotar o Racing por 3 a 2, nesta quarta-feira (15), no estádio El Cilindro, pela segunda rodada do Grupo E da Copa Sul-Americana 2026. A equipe argentina abriu o placar logo aos 3 minutos com Santiago Sosa, que aproveitou falha defensiva do Botafogo após cobrança [&#8230;]",
    "lede": "Jogadores do Botafogo celebram gol de Júnior Santos • Vitor Silva/Botafogo \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/55210501855_9ca6af6e9f_o-300x200.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/55210501855_9ca6af6e9f_o-1200x800.webp\" O Botafogo conquistou uma importante vitória fora de casa ao derrotar o Racing por 3 a 2, nesta quarta-feira (15), no estádio El Cilindro, pela segunda rodada do Grupo E da Copa Sul-Americana 2026. A equipe argentina abriu o placar logo aos 3 minutos com Santiago Sosa, que aproveitou falha defensiva do Botafogo após cobrança [&#8230;]",
    "url": "https://ac24horas.com/2026/04/15/danilo-decide-no-fim-e-botafogo-vence-o-racing-na-sul-americana/",
    "sourceUrl": "https://ac24horas.com/2026/04/15/danilo-decide-no-fim-e-botafogo-vence-o-racing-na-sul-americana/",
    "sourceName": "ac24horas",
    "sourceLabel": "Danilo decide no fim, e Botafogo vence o Racing na Sul-Americana",
    "category": "Esporte",
    "publishedAt": "2026-04-16T01:25:10.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/55210501855_9ca6af6e9f_o-1200x800.webp",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/55210501855_9ca6af6e9f_o-1200x800.webp",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/55210501855_9ca6af6e9f_o-1200x800.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/15/independencia-leva-virada-do-paysandu-e-e-eliminado-da-copa-verde/",
    "slug": "independencia-leva-virada-do-paysandu-e-e-eliminado-da-copa-verde",
    "title": "Independência leva virada do Paysandu e é eliminado da Copa Verde",
    "summary": "Foto: Alex Daniel Oliveira &#8211; Paysandu venceu e segue com chances de disputar a semifinal \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T194351.813-300x214.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T194351.813.jpg\" O Independência perdeu para o Paysandu por 2 a 1, de virada, nesta quarta, 15, na Curuzu, em Belém, no Pará. Juninho e Salomoni marcaram os gols do Papão enquanto Diego anotou para o Tricolor. Penalidade inexistente O árbitro Bruno Vieira, de Goiás, marcou uma penalidade inexistente para o Paysandu nos acréscimo do primeiro tempo [&#8230;]",
    "lede": "Foto: Alex Daniel Oliveira &#8211; Paysandu venceu e segue com chances de disputar a semifinal \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T194351.813-300x214.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T194351.813.jpg\" O Independência perdeu para o Paysandu por 2 a 1, de virada, nesta quarta, 15, na Curuzu, em Belém, no Pará. Juninho e Salomoni marcaram os gols do Papão enquanto Diego anotou para o Tricolor. Penalidade inexistente O árbitro Bruno Vieira, de Goiás, marcou uma penalidade inexistente para o Paysandu nos acréscimo do primeiro tempo [&#8230;]",
    "url": "https://ac24horas.com/2026/04/15/independencia-leva-virada-do-paysandu-e-e-eliminado-da-copa-verde/",
    "sourceUrl": "https://ac24horas.com/2026/04/15/independencia-leva-virada-do-paysandu-e-e-eliminado-da-copa-verde/",
    "sourceName": "ac24horas",
    "sourceLabel": "Independência leva virada do Paysandu e é eliminado da Copa Verde",
    "category": "Esporte",
    "publishedAt": "2026-04-16T00:49:18.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T194351.813.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T194351.813.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-14-16-51-43-1200x801.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/15/mensagens-de-bob-sinclar-christian-chavez-e-mais-artistas-marcam-festa-do-bbb-26-saiba-mais/",
    "slug": "mensagens-de-bob-sinclar-christian-chavez-e-mais-artistas-marcam-festa-do-bbb-26-saiba-mais",
    "title": "Mensagens de Bob Sinclar, Christian Chávez e mais artistas marcam Festa do BBB 26; saiba mais",
    "summary": "Nesta quarta-feira (15), os participantes do Top 5 do BBB 26 e o público poderão curtir uma noite do pijama na sala mais vigiada do país, revivendo juntos os momentos mais marcantes das festas. Através de uma cápsula do tempo, será possível escolher trechos de shows, músicas que viraram hit na temporada e VT’s que [&#8230;]",
    "lede": "Nesta quarta-feira (15), os participantes do Top 5 do BBB 26 e o público poderão curtir uma noite do pijama na sala mais vigiada do país, revivendo juntos os momentos mais marcantes das festas. Através de uma cápsula do tempo, será possível escolher trechos de shows, músicas que viraram hit na temporada e VT’s que [&#8230;]",
    "url": "https://ac24horas.com/2026/04/15/mensagens-de-bob-sinclar-christian-chavez-e-mais-artistas-marcam-festa-do-bbb-26-saiba-mais/",
    "sourceUrl": "https://ac24horas.com/2026/04/15/mensagens-de-bob-sinclar-christian-chavez-e-mais-artistas-marcam-festa-do-bbb-26-saiba-mais/",
    "sourceName": "ac24horas",
    "sourceLabel": "Mensagens de Bob Sinclar, Christian Chávez e mais artistas marcam Festa do BBB 26; saiba mais",
    "category": "Negócios",
    "publishedAt": "2026-04-16T00:42:08.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-15-at-19.32.32.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-15-at-19.32.32.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-15-at-19.32.32.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/15/gilmar-entra-com-acao-contra-relator-da-cpi-do-crime-organizado/",
    "slug": "gilmar-entra-com-acao-contra-relator-da-cpi-do-crime-organizado",
    "title": "Gilmar entra com ação contra relator da CPI do Crime Organizado",
    "summary": "Foto: Victor Piemonte/STF \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/gilmar-mendes-300x200.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/gilmar-mendes.webp\" O ministro do STF (Supremo Tribunal Federal) Gilmar Mendes ingressou nesta quarta-feira (15) com uma ação contra o senador Alessandro Vieira (MDB-SE), relator da CPI do Crime Organizado, após o parlamentar ter solicitado o indiciamento de integrantes da Corte. O documento foi encaminhado ao procurador-geral da República, Paulo Gonet. O decano do STF alega que [&#8230;]",
    "lede": "Foto: Victor Piemonte/STF \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/gilmar-mendes-300x200.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/gilmar-mendes.webp\" O ministro do STF (Supremo Tribunal Federal) Gilmar Mendes ingressou nesta quarta-feira (15) com uma ação contra o senador Alessandro Vieira (MDB-SE), relator da CPI do Crime Organizado, após o parlamentar ter solicitado o indiciamento de integrantes da Corte. O documento foi encaminhado ao procurador-geral da República, Paulo Gonet. O decano do STF alega que [&#8230;]",
    "url": "https://ac24horas.com/2026/04/15/gilmar-entra-com-acao-contra-relator-da-cpi-do-crime-organizado/",
    "sourceUrl": "https://ac24horas.com/2026/04/15/gilmar-entra-com-acao-contra-relator-da-cpi-do-crime-organizado/",
    "sourceName": "ac24horas",
    "sourceLabel": "Gilmar entra com ação contra relator da CPI do Crime Organizado",
    "category": "Polícia",
    "publishedAt": "2026-04-16T00:30:34.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/gilmar-mendes.webp",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/gilmar-mendes.webp",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/gilmar-mendes-1200x686.webp"
  },
  {
    "id": "https://ac24horas.com/2026/04/15/ramagem-e-solto-nos-eua-apos-ser-detido-pelo-ice/",
    "slug": "ramagem-e-solto-nos-eua-apos-ser-detido-pelo-ice",
    "title": "Ramagem é solto nos EUA após ser detido pelo ICE",
    "summary": "Deputado federal Alexandre Ramagem (PL-RJ), em entrevista à CNN • Reprodução/CNN \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/CNN_889fa0-300x169.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/CNN_889fa0.webp\" O ex-deputado federal Alexandre Ramagem, detido nos Estados Unidos na última segunda-feira (13) pelo ICE (Serviço de Imigração e Controle de Aduanas dos EUA) , foi solto nesta quarta-feira (15), segundo informações da PF (Polícia Federal). À CNN Brasil, o empresário e apresentador Paulo Figueiredo, que está nos EUA e acompanha o caso, afirmou que [&#8230;]",
    "lede": "Deputado federal Alexandre Ramagem (PL-RJ), em entrevista à CNN • Reprodução/CNN \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/CNN_889fa0-300x169.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/CNN_889fa0.webp\" O ex-deputado federal Alexandre Ramagem, detido nos Estados Unidos na última segunda-feira (13) pelo ICE (Serviço de Imigração e Controle de Aduanas dos EUA) , foi solto nesta quarta-feira (15), segundo informações da PF (Polícia Federal). À CNN Brasil, o empresário e apresentador Paulo Figueiredo, que está nos EUA e acompanha o caso, afirmou que [&#8230;]",
    "url": "https://ac24horas.com/2026/04/15/ramagem-e-solto-nos-eua-apos-ser-detido-pelo-ice/",
    "sourceUrl": "https://ac24horas.com/2026/04/15/ramagem-e-solto-nos-eua-apos-ser-detido-pelo-ice/",
    "sourceName": "ac24horas",
    "sourceLabel": "Ramagem é solto nos EUA após ser detido pelo ICE",
    "category": "Polícia",
    "publishedAt": "2026-04-16T00:06:50.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/CNN_889fa0.webp",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/CNN_889fa0.webp",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/CNN_889fa0.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/15/foto-em-brasilia-reune-alan-rick-flavio-bolsonaro-e-marcio-bittar/",
    "slug": "foto-em-brasilia-reune-alan-rick-flavio-bolsonaro-e-marcio-bittar",
    "title": "Foto em Brasília reúne Alan Rick, Flávio Bolsonaro e Márcio Bittar",
    "summary": "Foto: Instagram/ reprodução \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T185824.762-300x214.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T185824.762.jpg\" O senador Alan Rick (Republicanos) publicou nas redes sociais nesta quarta-feira, 15, uma foto ao lado do senador Flávio Bolsonaro e do senador Marcio Bittar, ambos do PL. Na legenda, Alan Rick chamou Flávio de “nosso futuro presidente” e afirmou que o grupo trabalha na construção do “Brasil que queremos”. Na publicação, o parlamentar destacou [&#8230;]",
    "lede": "Foto: Instagram/ reprodução \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T185824.762-300x214.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T185824.762.jpg\" O senador Alan Rick (Republicanos) publicou nas redes sociais nesta quarta-feira, 15, uma foto ao lado do senador Flávio Bolsonaro e do senador Marcio Bittar, ambos do PL. Na legenda, Alan Rick chamou Flávio de “nosso futuro presidente” e afirmou que o grupo trabalha na construção do “Brasil que queremos”. Na publicação, o parlamentar destacou [&#8230;]",
    "url": "https://ac24horas.com/2026/04/15/foto-em-brasilia-reune-alan-rick-flavio-bolsonaro-e-marcio-bittar/",
    "sourceUrl": "https://ac24horas.com/2026/04/15/foto-em-brasilia-reune-alan-rick-flavio-bolsonaro-e-marcio-bittar/",
    "sourceName": "ac24horas",
    "sourceLabel": "Foto em Brasília reúne Alan Rick, Flávio Bolsonaro e Márcio Bittar",
    "category": "Política",
    "publishedAt": "2026-04-16T00:00:24.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T185824.762.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T185824.762.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-15-16-02-20-1200x801.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/15/ciclista-acreano-chega-no-panama-para-disputa-do-sul-americano-da-juventude/",
    "slug": "ciclista-acreano-chega-no-panama-para-disputa-do-sul-americano-da-juventude",
    "title": "Ciclista acreano chega no Panamá para disputa do Sul-Americano da Juventude",
    "summary": "O ciclista acreano Danilo Silva iniciou nesta quarta, 15, na Cidade do Panamá, no Panamá, a última etapa de preparação visando à disputa dos Jogos Sul-Americanos da Juventude. A competição vai ser disputada entre os dias 16 e 18 deste mês e a Seleção Brasileira chega com uma equipe forte para a competição. “Realizamos o [&#8230;]",
    "lede": "O ciclista acreano Danilo Silva iniciou nesta quarta, 15, na Cidade do Panamá, no Panamá, a última etapa de preparação visando à disputa dos Jogos Sul-Americanos da Juventude. A competição vai ser disputada entre os dias 16 e 18 deste mês e a Seleção Brasileira chega com uma equipe forte para a competição. “Realizamos o [&#8230;]",
    "url": "https://ac24horas.com/2026/04/15/ciclista-acreano-chega-no-panama-para-disputa-do-sul-americano-da-juventude/",
    "sourceUrl": "https://ac24horas.com/2026/04/15/ciclista-acreano-chega-no-panama-para-disputa-do-sul-americano-da-juventude/",
    "sourceName": "ac24horas",
    "sourceLabel": "Ciclista acreano chega no Panamá para disputa do Sul-Americano da Juventude",
    "category": "Esporte",
    "publishedAt": "2026-04-15T23:29:28.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T182653.242.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T182653.242.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-15-at-17.49.44-1029x1200.jpeg"
  },
  {
    "id": "https://ac24horas.com/2026/04/15/bolsa-interrompe-sequencia-de-11-altas-e-cai-046/",
    "slug": "bolsa-interrompe-sequencia-de-11-altas-e-cai-0-46",
    "title": "Bolsa interrompe sequência de 11 altas e cai 0,46%",
    "summary": "Foto: REUTERS/Paulo Whitaker \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/2020-03-11t154713z_1_lynxmpeg2a1pf_rtroptp_4_bovespa-manh-300x179.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/2020-03-11t154713z_1_lynxmpeg2a1pf_rtroptp_4_bovespa-manh.jpg\" Num dia de cautela no mercado financeiro, a bolsa de valores interrompeu uma sequência altas e teve leve queda. O dólar ficou praticamente estável, permanecendo abaixo de R$ 5. Na falta de novos sinais no cenário externo, investidores venderam ações para embolsar lucros recentes, enquanto o petróleo teve sessão volátil e fechou perto da estabilidade. [&#8230;]",
    "lede": "Foto: REUTERS/Paulo Whitaker \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/2020-03-11t154713z_1_lynxmpeg2a1pf_rtroptp_4_bovespa-manh-300x179.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/2020-03-11t154713z_1_lynxmpeg2a1pf_rtroptp_4_bovespa-manh.jpg\" Num dia de cautela no mercado financeiro, a bolsa de valores interrompeu uma sequência altas e teve leve queda. O dólar ficou praticamente estável, permanecendo abaixo de R$ 5. Na falta de novos sinais no cenário externo, investidores venderam ações para embolsar lucros recentes, enquanto o petróleo teve sessão volátil e fechou perto da estabilidade. [&#8230;]",
    "url": "https://ac24horas.com/2026/04/15/bolsa-interrompe-sequencia-de-11-altas-e-cai-046/",
    "sourceUrl": "https://ac24horas.com/2026/04/15/bolsa-interrompe-sequencia-de-11-altas-e-cai-046/",
    "sourceName": "ac24horas",
    "sourceLabel": "Bolsa interrompe sequência de 11 altas e cai 0,46%",
    "category": "Negócios",
    "publishedAt": "2026-04-15T23:13:32.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/2020-03-11t154713z_1_lynxmpeg2a1pf_rtroptp_4_bovespa-manh.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/2020-03-11t154713z_1_lynxmpeg2a1pf_rtroptp_4_bovespa-manh.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-15-at-16.58.34-1200x765.jpeg"
  },
  {
    "id": "https://ac24horas.com/2026/04/15/governo-propoe-superavit-primario-de-r-73-bilhoes-para-2027/",
    "slug": "governo-propoe-superavit-primario-de-r-73-bilhoes-para-2027",
    "title": "Governo propõe superávit primário de R$ 73 bilhões para 2027",
    "summary": "Foto: José Cruz/Agência Brasil/Arquivo \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/real_moedadinheiro_jfcrz_abr_1701220049_1-300x179.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/real_moedadinheiro_jfcrz_abr_1701220049_1.webp\" A equipe econômica propôs uma meta de superávit primário de R$ 73,2 bilhões para 2027, primeiro ano do próximo mandato presidencial. O valor corresponde a 0,5% do Produto Interno Bruto (PIB) e foi apresentado no Projeto de Lei de Diretrizes Orçamentárias (PLDO) enviado ao Congresso Nacional nesta quarta-feira (15). Apesar da meta ambiciosa, o resultado [&#8230;]",
    "lede": "Foto: José Cruz/Agência Brasil/Arquivo \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/real_moedadinheiro_jfcrz_abr_1701220049_1-300x179.webp\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/real_moedadinheiro_jfcrz_abr_1701220049_1.webp\" A equipe econômica propôs uma meta de superávit primário de R$ 73,2 bilhões para 2027, primeiro ano do próximo mandato presidencial. O valor corresponde a 0,5% do Produto Interno Bruto (PIB) e foi apresentado no Projeto de Lei de Diretrizes Orçamentárias (PLDO) enviado ao Congresso Nacional nesta quarta-feira (15). Apesar da meta ambiciosa, o resultado [&#8230;]",
    "url": "https://ac24horas.com/2026/04/15/governo-propoe-superavit-primario-de-r-73-bilhoes-para-2027/",
    "sourceUrl": "https://ac24horas.com/2026/04/15/governo-propoe-superavit-primario-de-r-73-bilhoes-para-2027/",
    "sourceName": "ac24horas",
    "sourceLabel": "Governo propõe superávit primário de R$ 73 bilhões para 2027",
    "category": "Prefeitura",
    "publishedAt": "2026-04-15T22:42:13.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/real_moedadinheiro_jfcrz_abr_1701220049_1.webp",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/real_moedadinheiro_jfcrz_abr_1701220049_1.webp",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-15-at-16.58.34-1200x765.jpeg"
  },
  {
    "id": "https://ac24horas.com/2026/04/15/governo-estima-salario-minimo-de-r-1-717-em-2027/",
    "slug": "governo-estima-salario-minimo-de-r-1-717-em-2027",
    "title": "Governo estima salário mínimo de R$ 1.717 em 2027",
    "summary": "Foto: Reprodução/Pixabay \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/dinheiro-300x200.avif\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/dinheiro.avif\" O governo federal estima que o salário mínimo suba para R$ 1.717 em janeiro de 2027, com pagamento a partir de fevereiro. A projeção está no projeto de Lei de Diretrizes Orçamentárias (PLDO) de 2027, que será enviado nesta quarta-feira (15) ao Congresso Nacional. A LDO é a norma que define as metas e prioridades [&#8230;]",
    "lede": "Foto: Reprodução/Pixabay \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/dinheiro-300x200.avif\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/dinheiro.avif\" O governo federal estima que o salário mínimo suba para R$ 1.717 em janeiro de 2027, com pagamento a partir de fevereiro. A projeção está no projeto de Lei de Diretrizes Orçamentárias (PLDO) de 2027, que será enviado nesta quarta-feira (15) ao Congresso Nacional. A LDO é a norma que define as metas e prioridades [&#8230;]",
    "url": "https://ac24horas.com/2026/04/15/governo-estima-salario-minimo-de-r-1-717-em-2027/",
    "sourceUrl": "https://ac24horas.com/2026/04/15/governo-estima-salario-minimo-de-r-1-717-em-2027/",
    "sourceName": "ac24horas",
    "sourceLabel": "Governo estima salário mínimo de R$ 1.717 em 2027",
    "category": "Utilidade Pública",
    "publishedAt": "2026-04-15T22:37:52.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/dinheiro.avif",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/dinheiro.avif",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-15-at-16.58.34-1200x765.jpeg"
  },
  {
    "id": "https://ac24horas.com/2026/04/15/jordana-detona-jogo-de-ana-paula-renault-cria-o-assunto-certo/",
    "slug": "jordana-detona-jogo-de-ana-paula-renault-8216-cria-o-assunto-certo-8217",
    "title": "Jordana detona jogo de Ana Paula Renault: &#8216;Cria o assunto certo&#8217;",
    "summary": "BBB 26: Jordana analisa jogo de Ana Paula Renault-Imagem: Reprodução/Globoplay \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/bbb-26-jordana-analisa-jogo-de-ana-paula-renault-1776288867785_v2_900x506.jpg-300x169.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/bbb-26-jordana-analisa-jogo-de-ana-paula-renault-1776288867785_v2_900x506.jpg.jpg\" Sozinha na área externa do BBB 26 (Globo), Jordana analisou o jogo de Ana Paula. O que aconteceu Os confrontos entre as duas sisters se intensificaram nos últimos dias. Jordana criticou Ana Paula enquanto falava sozinha. &#8220;Ana Paula está criando os diálogos certos para limpar a barra dela e do Juliano. É tão perceptível. Cria [&#8230;]",
    "lede": "BBB 26: Jordana analisa jogo de Ana Paula Renault-Imagem: Reprodução/Globoplay \" data-medium-file=\"https://ac24horas.com/wp-content/uploads/2026/04/bbb-26-jordana-analisa-jogo-de-ana-paula-renault-1776288867785_v2_900x506.jpg-300x169.jpg\" data-large-file=\"https://ac24horas.com/wp-content/uploads/2026/04/bbb-26-jordana-analisa-jogo-de-ana-paula-renault-1776288867785_v2_900x506.jpg.jpg\" Sozinha na área externa do BBB 26 (Globo), Jordana analisou o jogo de Ana Paula. O que aconteceu Os confrontos entre as duas sisters se intensificaram nos últimos dias. Jordana criticou Ana Paula enquanto falava sozinha. &#8220;Ana Paula está criando os diálogos certos para limpar a barra dela e do Juliano. É tão perceptível. Cria [&#8230;]",
    "url": "https://ac24horas.com/2026/04/15/jordana-detona-jogo-de-ana-paula-renault-cria-o-assunto-certo/",
    "sourceUrl": "https://ac24horas.com/2026/04/15/jordana-detona-jogo-de-ana-paula-renault-cria-o-assunto-certo/",
    "sourceName": "ac24horas",
    "sourceLabel": "Jordana detona jogo de Ana Paula Renault: &#8216;Cria o assunto certo&#8217;",
    "category": "Esporte",
    "publishedAt": "2026-04-15T22:24:30.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/bbb-26-jordana-analisa-jogo-de-ana-paula-renault-1776288867785_v2_900x506.jpg.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/bbb-26-jordana-analisa-jogo-de-ana-paula-renault-1776288867785_v2_900x506.jpg.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-15-at-16.58.34-1200x765.jpeg"
  },
  {
    "id": "https://ac24horas.com/2026/04/15/detento-que-fugiu-do-presidio-pode-estar-envolvido-em-uma-serie-de-crimes/",
    "slug": "detento-que-fugiu-do-presidio-pode-estar-envolvido-em-uma-serie-de-crimes",
    "title": "Detento que fugiu do presídio pode estar envolvido em uma série de crimes",
    "summary": "O foragido Ozéia Paulo Germano Ferreira, que escapou do presídio Francisco de Oliveira Conde em junho do ano passado, é apontado pela polícia como suspeito de envolvimento em uma série de crimes de roubos e furtos registrados em Rio Branco. No próximo dia 19, a fuga do criminoso completa nove meses. Durante esse período, segundo [&#8230;]",
    "lede": "O foragido Ozéia Paulo Germano Ferreira, que escapou do presídio Francisco de Oliveira Conde em junho do ano passado, é apontado pela polícia como suspeito de envolvimento em uma série de crimes de roubos e furtos registrados em Rio Branco. No próximo dia 19, a fuga do criminoso completa nove meses. Durante esse período, segundo [&#8230;]",
    "url": "https://ac24horas.com/2026/04/15/detento-que-fugiu-do-presidio-pode-estar-envolvido-em-uma-serie-de-crimes/",
    "sourceUrl": "https://ac24horas.com/2026/04/15/detento-que-fugiu-do-presidio-pode-estar-envolvido-em-uma-serie-de-crimes/",
    "sourceName": "ac24horas",
    "sourceLabel": "Detento que fugiu do presídio pode estar envolvido em uma série de crimes",
    "category": "Polícia",
    "publishedAt": "2026-04-15T22:14:14.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T171347.712.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T171347.712.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-15-16-02-20-1200x801.avif"
  },
  {
    "id": "https://ac24horas.com/2026/04/15/acao-gratuita-reune-servicos-juridicos-e-de-saude-para-pessoas-com-autismo-em-rio-branco-neste-sabado/",
    "slug": "acao-gratuita-reune-servicos-juridicos-e-de-saude-para-pessoas-com-autismo-neste-sabado",
    "title": "Ação gratuita reúne serviços jurídicos e de saúde para pessoas com autismo neste sábado",
    "summary": "A Defensoria Pública do Acre (DPE/AC) realiza, neste sábado (18), em Rio Branco, uma ação especial em alusão ao Dia Mundial de Conscientização do Autismo. O evento é gratuito e tem como objetivo acolher, orientar e garantir os direitos das pessoas com Transtorno do Espectro Autista (TEA) e de suas famílias. A programação acontece das [&#8230;]",
    "lede": "A Defensoria Pública do Acre (DPE/AC) realiza, neste sábado (18), em Rio Branco, uma ação especial em alusão ao Dia Mundial de Conscientização do Autismo. O evento é gratuito e tem como objetivo acolher, orientar e garantir os direitos das pessoas com Transtorno do Espectro Autista (TEA) e de suas famílias. A programação acontece das [&#8230;]",
    "url": "https://ac24horas.com/2026/04/15/acao-gratuita-reune-servicos-juridicos-e-de-saude-para-pessoas-com-autismo-em-rio-branco-neste-sabado/",
    "sourceUrl": "https://ac24horas.com/2026/04/15/acao-gratuita-reune-servicos-juridicos-e-de-saude-para-pessoas-com-autismo-em-rio-branco-neste-sabado/",
    "sourceName": "ac24horas",
    "sourceLabel": "Ação gratuita reúne serviços jurídicos e de saúde para pessoas com autismo neste sábado",
    "category": "Cotidiano",
    "publishedAt": "2026-04-15T22:10:22.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T170923.770.jpg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/976x695_IMAGEM-DESTACADA-2026-04-15T170923.770.jpg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-15-at-12.38.43-1200x675.jpeg"
  },
  {
    "id": "https://ac24horas.com/2026/04/15/camara-tecnica-de-comercio-exterior-celebra-lancamento-de-servico-voltado-para-negocios-internacionais/",
    "slug": "camara-tecnica-de-comercio-celebra-servico-voltado-ao-comercio-exterior",
    "title": "Câmara Técnica de Comércio celebra serviço voltado ao comércio exterior",
    "summary": "O lançamento do Departamento de Importação e Exportação da Calegari Contabilidade, em Rio Branco, na terça-feira, 14, foi celebrado pela Câmara Técnica de Comércio Exterior do Fórum Empresarial de Inovação e Desenvolvimento do Acre. O evento reuniu empresários, entidades e especialistas da área em um encontro voltado à expansão de negócios e à ampliação da [&#8230;]",
    "lede": "O lançamento do Departamento de Importação e Exportação da Calegari Contabilidade, em Rio Branco, na terça-feira, 14, foi celebrado pela Câmara Técnica de Comércio Exterior do Fórum Empresarial de Inovação e Desenvolvimento do Acre. O evento reuniu empresários, entidades e especialistas da área em um encontro voltado à expansão de negócios e à ampliação da [&#8230;]",
    "url": "https://ac24horas.com/2026/04/15/camara-tecnica-de-comercio-exterior-celebra-lancamento-de-servico-voltado-para-negocios-internacionais/",
    "sourceUrl": "https://ac24horas.com/2026/04/15/camara-tecnica-de-comercio-exterior-celebra-lancamento-de-servico-voltado-para-negocios-internacionais/",
    "sourceName": "ac24horas",
    "sourceLabel": "Câmara Técnica de Comércio celebra serviço voltado ao comércio exterior",
    "category": "Utilidade Pública",
    "publishedAt": "2026-04-15T22:04:48.000Z",
    "imageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-15-at-16.58.34-1200x765.jpeg",
    "feedImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-15-at-16.58.34-1200x765.jpeg",
    "sourceImageUrl": "https://ac24horas.com/wp-content/uploads/2026/04/PHOTO-2026-04-15-16-02-20-1200x801.avif"
  },
  {
    "id": "https://agencia.ac.gov.br/governadora-mailza-assis-empossa-novo-delegado-geral-e-anuncia-concurso-publico-da-policia-civil/",
    "slug": "governadora-mailza-assis-empossa-novo-delegado-geral-e-anuncia-concurso-publico-da-policia-civil",
    "title": "Governadora Mailza Assis empossa novo delegado-geral e anuncia concurso público da Polícia Civil",
    "summary": "Em mais um passo para o fortalecimento da Segurança Pública no estado, a governadora Mailza Assis deu posse, nesta quarta-feira, 15, ao novo delegado-geral da Polícia Civil do Acre (PCAC), Pedro Paulo Buzolin. Na ocasião, também anunciou a realização de concurso público para reforçar o quadro da instituição, com vagas para delegado, oficial investigador de [&#8230;] The post Governadora Mailza Assis empossa novo delegado-geral e anuncia concurso público da Polícia Civil appeared first on Noticias do Acre .",
    "lede": "Em mais um passo para o fortalecimento da Segurança Pública no estado, a governadora Mailza Assis deu posse, nesta quarta-feira, 15, ao novo delegado-geral da Polícia Civil do Acre (PCAC), Pedro Paulo Buzolin. Na ocasião, também anunciou a realização de concurso público para reforçar o quadro da instituição, com vagas para delegado, oficial investigador de [&#8230;] The post Governadora Mailza Assis empossa novo delegado-geral e anuncia concurso público da Polícia Civil appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/governadora-mailza-assis-empossa-novo-delegado-geral-e-anuncia-concurso-publico-da-policia-civil/",
    "sourceUrl": "https://agencia.ac.gov.br/governadora-mailza-assis-empossa-novo-delegado-geral-e-anuncia-concurso-publico-da-policia-civil/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Governadora Mailza Assis empossa novo delegado-geral e anuncia concurso público da Polícia Civil",
    "category": "Polícia",
    "publishedAt": "2026-04-15T23:34:09.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/115914b3-68cf-4038-9868-047f637d8f77-1-1024x681.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/115914b3-68cf-4038-9868-047f637d8f77-1-1024x681.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/115914b3-68cf-4038-9868-047f637d8f77-1-1024x681.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/gestores-visitam-nova-sede-da-seict-e-reforcam-estrategia-de-inovacao-com-o-parque-tecnologico-de-rio-branco/",
    "slug": "gestores-visitam-nova-sede-da-seict-e-reforcam-estrategia-de-inovacao-com-o-parque-tecnologico-de-rio-branco",
    "title": "Gestores visitam nova sede da Seict e reforçam estratégia de inovação com o Parque Tecnológico de Rio Branco",
    "summary": "Gestores do governo do Acre, por meio da Secretaria de Estado de Indústria, Ciência e Tecnologia (Seict), realizaram uma visita técnica à nova sede da pasta, no complexo Via Towers, em Rio Branco, nesta quarta-feira, 15. A agenda foi conduzida pelo titular do órgão, Márcio Agiolfi, que conheceu a estrutura que vai abrigar as atividades [&#8230;] The post Gestores visitam nova sede da Seict e reforçam estratégia de inovação com o Parque Tecnológico de Rio Branco appeared first on Noticias do Acre .",
    "lede": "Gestores do governo do Acre, por meio da Secretaria de Estado de Indústria, Ciência e Tecnologia (Seict), realizaram uma visita técnica à nova sede da pasta, no complexo Via Towers, em Rio Branco, nesta quarta-feira, 15. A agenda foi conduzida pelo titular do órgão, Márcio Agiolfi, que conheceu a estrutura que vai abrigar as atividades [&#8230;] The post Gestores visitam nova sede da Seict e reforçam estratégia de inovação com o Parque Tecnológico de Rio Branco appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/gestores-visitam-nova-sede-da-seict-e-reforcam-estrategia-de-inovacao-com-o-parque-tecnologico-de-rio-branco/",
    "sourceUrl": "https://agencia.ac.gov.br/gestores-visitam-nova-sede-da-seict-e-reforcam-estrategia-de-inovacao-com-o-parque-tecnologico-de-rio-branco/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Gestores visitam nova sede da Seict e reforçam estratégia de inovação com o Parque Tecnológico de Rio Branco",
    "category": "Prefeitura",
    "publishedAt": "2026-04-15T19:55:29.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/visita-nova-sede-seict-capa-1024x576.jpg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/visita-nova-sede-seict-capa-1024x576.jpg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/visita-nova-sede-seict-capa-1024x576.jpg"
  },
  {
    "id": "https://agencia.ac.gov.br/educacao-do-acre-segue-com-manutencao-predial-em-escolas-indigenas-de-sena-madureira/",
    "slug": "educacao-do-acre-segue-com-manutencao-predial-em-escolas-indigenas-de-sena-madureira",
    "title": "Educação do Acre segue com manutenção predial em escolas indígenas de Sena Madureira",
    "summary": "A Secretaria de Estado de Educação e Cultura (SEE) segue com a manutenção predial em diversas escolas indígenas do Acre, sobretudo no município de Sena Madureira, onde quatro escolas passam por um processo de revitalização, com investimento superior a R$ 1,2 milhão. As escolas que passam por revitalização no município são a Nawawae, com investimento [&#8230;] The post Educação do Acre segue com manutenção predial em escolas indígenas de Sena Madureira appeared first on Noticias do Acre .",
    "lede": "A Secretaria de Estado de Educação e Cultura (SEE) segue com a manutenção predial em diversas escolas indígenas do Acre, sobretudo no município de Sena Madureira, onde quatro escolas passam por um processo de revitalização, com investimento superior a R$ 1,2 milhão. As escolas que passam por revitalização no município são a Nawawae, com investimento [&#8230;] The post Educação do Acre segue com manutenção predial em escolas indígenas de Sena Madureira appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/educacao-do-acre-segue-com-manutencao-predial-em-escolas-indigenas-de-sena-madureira/",
    "sourceUrl": "https://agencia.ac.gov.br/educacao-do-acre-segue-com-manutencao-predial-em-escolas-indigenas-de-sena-madureira/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Educação do Acre segue com manutenção predial em escolas indígenas de Sena Madureira",
    "category": "Educação",
    "publishedAt": "2026-04-15T19:49:46.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/assis13-1024x768.jpg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/assis13-1024x768.jpg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/visita-nova-sede-seict-capa-1024x576.jpg"
  },
  {
    "id": "https://agencia.ac.gov.br/governadora-mailza-autoriza-inicio-da-2a-etapa-das-obras-de-urbanizacao-do-calcadao-do-mercado-velho-em-rio-branco/",
    "slug": "governadora-mailza-autoriza-inicio-da-2-etapa-das-obras-de-urbanizacao-do-calcadao-do-mercado-velho-em-rio-branco",
    "title": "Governadora Mailza autoriza início da 2ª etapa das obras de urbanização do Calçadão do Mercado Velho em Rio Branco",
    "summary": "A governadora Mailza Assis autorizou, nesta quarta-feira, 15, o início da segunda etapa das obras de urbanização do Calçadão do Mercado Velho, em Rio Branco, consolidando o compromisso do governo com a requalificação dos espaços públicos, valorização do patrimônio histórico-cultural e o fortalecimento da atividade econômica local. A ordem de serviço foi assinada em cerimônia [&#8230;] The post Governadora Mailza autoriza início da 2ª etapa das obras de urbanização do Calçadão do Mercado Velho em Rio Branco appeared first on Noticias do Acre .",
    "lede": "A governadora Mailza Assis autorizou, nesta quarta-feira, 15, o início da segunda etapa das obras de urbanização do Calçadão do Mercado Velho, em Rio Branco, consolidando o compromisso do governo com a requalificação dos espaços públicos, valorização do patrimônio histórico-cultural e o fortalecimento da atividade econômica local. A ordem de serviço foi assinada em cerimônia [&#8230;] The post Governadora Mailza autoriza início da 2ª etapa das obras de urbanização do Calçadão do Mercado Velho em Rio Branco appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/governadora-mailza-autoriza-inicio-da-2a-etapa-das-obras-de-urbanizacao-do-calcadao-do-mercado-velho-em-rio-branco/",
    "sourceUrl": "https://agencia.ac.gov.br/governadora-mailza-autoriza-inicio-da-2a-etapa-das-obras-de-urbanizacao-do-calcadao-do-mercado-velho-em-rio-branco/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Governadora Mailza autoriza início da 2ª etapa das obras de urbanização do Calçadão do Mercado Velho em Rio Branco",
    "category": "Utilidade Pública",
    "publishedAt": "2026-04-15T19:29:39.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/9615d2d3-f54b-4997-bc74-d5376ea6ffd1-1024x683.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/9615d2d3-f54b-4997-bc74-d5376ea6ffd1-1024x683.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/057125c5-5fe8-45ad-9781-64b85d1b8d8b-1024x683.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/estado-habilita-site-do-programa-nota-premiada-para-que-entidades-solicitem-premiacao-no-proprio-portal/",
    "slug": "estado-habilita-site-do-programa-nota-premiada-para-que-entidades-solicitem-premiacao-no-proprio-portal",
    "title": "Estado habilita site do programa Nota Premiada para que entidades solicitem premiação no próprio portal",
    "summary": "O portal institucional do programa Nota Premiada Acreana passou por mudanças para facilitar a solicitação de premiação por parte das entidades sociais sem fins lucrativos cadastradas no programa. Toda a tramitação já pode ser feita digitalmente dentro do site notapremiadaacreana.ac.gov.br. A partir de agora, as entidades não precisam mais aguardar o envio de um recibo [&#8230;] The post Estado habilita site do programa Nota Premiada para que entidades solicitem premiação no próprio portal appeared first on Noticias do Acre .",
    "lede": "O portal institucional do programa Nota Premiada Acreana passou por mudanças para facilitar a solicitação de premiação por parte das entidades sociais sem fins lucrativos cadastradas no programa. Toda a tramitação já pode ser feita digitalmente dentro do site notapremiadaacreana.ac.gov.br. A partir de agora, as entidades não precisam mais aguardar o envio de um recibo [&#8230;] The post Estado habilita site do programa Nota Premiada para que entidades solicitem premiação no próprio portal appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/estado-habilita-site-do-programa-nota-premiada-para-que-entidades-solicitem-premiacao-no-proprio-portal/",
    "sourceUrl": "https://agencia.ac.gov.br/estado-habilita-site-do-programa-nota-premiada-para-que-entidades-solicitem-premiacao-no-proprio-portal/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Estado habilita site do programa Nota Premiada para que entidades solicitem premiação no próprio portal",
    "category": "Negócios",
    "publishedAt": "2026-04-15T18:07:05.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/IMG_6460-1024x768.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/IMG_6460-1024x768.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/IMG_6460-1024x768.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/programa-pecuaria-mais-eficiente-fortalece-a-pecuaria-sustentavel-no-acre/",
    "slug": "programa-pecuaria-mais-eficiente-fortalece-a-pecuaria-sustentavel-no-acre",
    "title": "Programa Pecuária Mais Eficiente fortalece a pecuária sustentável no Acre",
    "summary": "O governo do Acre, por meio da Secretaria de Estado de Agricultura (Seagri), com apoio do Programa REM/KfW, segue avançando com ações voltadas ao fortalecimento da produção rural sustentável. Uma das iniciativas é o Programa Pecuária + Eficiente, que tem como foco a recuperação de pastagens degradadas e a redução do desmatamento no estado. Como [&#8230;] The post Programa Pecuária Mais Eficiente fortalece a pecuária sustentável no Acre appeared first on Noticias do Acre .",
    "lede": "O governo do Acre, por meio da Secretaria de Estado de Agricultura (Seagri), com apoio do Programa REM/KfW, segue avançando com ações voltadas ao fortalecimento da produção rural sustentável. Uma das iniciativas é o Programa Pecuária + Eficiente, que tem como foco a recuperação de pastagens degradadas e a redução do desmatamento no estado. Como [&#8230;] The post Programa Pecuária Mais Eficiente fortalece a pecuária sustentável no Acre appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/programa-pecuaria-mais-eficiente-fortalece-a-pecuaria-sustentavel-no-acre/",
    "sourceUrl": "https://agencia.ac.gov.br/programa-pecuaria-mais-eficiente-fortalece-a-pecuaria-sustentavel-no-acre/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Programa Pecuária Mais Eficiente fortalece a pecuária sustentável no Acre",
    "category": "Prefeitura",
    "publishedAt": "2026-04-15T17:38:20.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-14-at-08.09.31-1024x576.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-14-at-08.09.31-1024x576.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-14-at-11.33.27-819x1024.jpeg"
  },
  {
    "id": "https://agencia.ac.gov.br/pioneiras-do-taekwondo-no-acre-relembram-a-evolucao-do-esporte-marcada-pela-forca-feminina-que-desafiou-limites-e-quebrou-tabus/",
    "slug": "pioneiras-do-taekwondo-no-acre-relembram-a-evolucao-do-esporte-marcada-pela-forca-feminina-que-desafiou-limites-e-quebrou-tabus",
    "title": "Pioneiras do taekwondo no Acre relembram a evolução do esporte marcada pela força feminina que desafiou limites e quebrou tabus",
    "summary": "Pioneiras na representatividade feminina dentro de uma arte marcial coreana, marcada por chutes rápidos, altos e potentes, aliados à disciplina, ao respeito e ao desenvolvimento físico e mental, Susie de Matos, Aldeniza Fernandes e Carminda Pinheiro escreveram seus nomes na história do taekwondo no Acre. Agora, esse legado ganha registro oficial no livro “A história [&#8230;] The post Pioneiras do taekwondo no Acre relembram a evolução do esporte marcada pela força feminina que desafiou limites e quebrou tabus appeared first on Noticias do Acre .",
    "lede": "Pioneiras na representatividade feminina dentro de uma arte marcial coreana, marcada por chutes rápidos, altos e potentes, aliados à disciplina, ao respeito e ao desenvolvimento físico e mental, Susie de Matos, Aldeniza Fernandes e Carminda Pinheiro escreveram seus nomes na história do taekwondo no Acre. Agora, esse legado ganha registro oficial no livro “A história [&#8230;] The post Pioneiras do taekwondo no Acre relembram a evolução do esporte marcada pela força feminina que desafiou limites e quebrou tabus appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/pioneiras-do-taekwondo-no-acre-relembram-a-evolucao-do-esporte-marcada-pela-forca-feminina-que-desafiou-limites-e-quebrou-tabus/",
    "sourceUrl": "https://agencia.ac.gov.br/pioneiras-do-taekwondo-no-acre-relembram-a-evolucao-do-esporte-marcada-pela-forca-feminina-que-desafiou-limites-e-quebrou-tabus/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Pioneiras do taekwondo no Acre relembram a evolução do esporte marcada pela força feminina que desafiou limites e quebrou tabus",
    "category": "Esporte",
    "publishedAt": "2026-04-15T17:08:59.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-13-at-14.03.22-2-813x1024.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-13-at-14.03.22-2-813x1024.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/assis1-1024x576.jpg"
  },
  {
    "id": "https://agencia.ac.gov.br/educacao-do-acre-realiza-investimentos-em-escolas-indigenas-de-assis-brasil/",
    "slug": "educacao-do-acre-realiza-investimentos-em-escolas-indigenas-de-assis-brasil",
    "title": "Educação do Acre realiza investimentos em escolas indígenas de Assis Brasil",
    "summary": "A Secretaria de Estado de Educação e Cultura (SEE) segue com investimentos nas escolas indígenas do Acre. Mais de R$ 900 mil foram investidos na construção de três escolas localizadas na terra indígena Riozinho do Iaco, contemplando as etnias Manchineri e Jaminawa. As escolas indígenas construídas são a Homha, a Ushe, da etnia Jaminawa, e [&#8230;] The post Educação do Acre realiza investimentos em escolas indígenas de Assis Brasil appeared first on Noticias do Acre .",
    "lede": "A Secretaria de Estado de Educação e Cultura (SEE) segue com investimentos nas escolas indígenas do Acre. Mais de R$ 900 mil foram investidos na construção de três escolas localizadas na terra indígena Riozinho do Iaco, contemplando as etnias Manchineri e Jaminawa. As escolas indígenas construídas são a Homha, a Ushe, da etnia Jaminawa, e [&#8230;] The post Educação do Acre realiza investimentos em escolas indígenas de Assis Brasil appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/educacao-do-acre-realiza-investimentos-em-escolas-indigenas-de-assis-brasil/",
    "sourceUrl": "https://agencia.ac.gov.br/educacao-do-acre-realiza-investimentos-em-escolas-indigenas-de-assis-brasil/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Educação do Acre realiza investimentos em escolas indígenas de Assis Brasil",
    "category": "Educação",
    "publishedAt": "2026-04-15T16:44:26.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/assis3-1024x576.jpg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/assis3-1024x576.jpg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/IMG_8384-1024x643.jpg"
  },
  {
    "id": "https://agencia.ac.gov.br/educacao-do-acre-promove-capacitacao-sobre-gestao-e-fiscalizacao-de-contratos-administrativos-com-uso-de-inteligencia-artificial/",
    "slug": "educacao-do-acre-promove-capacitacao-sobre-gestao-e-fiscalizacao-de-contratos-administrativos-com-uso-de-inteligencia-artificial",
    "title": "Educação do Acre promove capacitação sobre gestão e fiscalização de contratos administrativos com uso de inteligência artificial",
    "summary": "A Secretaria de Estado de Educação e Cultura (SEE) realiza, de segunda a quinta-feira, de 13 a 16, a Capacitação em Contratação, Gestão e Fiscalização de Contratos Administrativos e Ferramentas de Inteligência Artificial. A formação ocorre no Espaço Formar, sala térreo do prédio da Secretaria Adjunta de Ensino, em Rio Branco. A capacitação disponibiliza 40 [&#8230;] The post Educação do Acre promove capacitação sobre gestão e fiscalização de contratos administrativos com uso de inteligência artificial appeared first on Noticias do Acre .",
    "lede": "A Secretaria de Estado de Educação e Cultura (SEE) realiza, de segunda a quinta-feira, de 13 a 16, a Capacitação em Contratação, Gestão e Fiscalização de Contratos Administrativos e Ferramentas de Inteligência Artificial. A formação ocorre no Espaço Formar, sala térreo do prédio da Secretaria Adjunta de Ensino, em Rio Branco. A capacitação disponibiliza 40 [&#8230;] The post Educação do Acre promove capacitação sobre gestão e fiscalização de contratos administrativos com uso de inteligência artificial appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/educacao-do-acre-promove-capacitacao-sobre-gestao-e-fiscalizacao-de-contratos-administrativos-com-uso-de-inteligencia-artificial/",
    "sourceUrl": "https://agencia.ac.gov.br/educacao-do-acre-promove-capacitacao-sobre-gestao-e-fiscalizacao-de-contratos-administrativos-com-uso-de-inteligencia-artificial/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Educação do Acre promove capacitação sobre gestão e fiscalização de contratos administrativos com uso de inteligência artificial",
    "category": "Educação",
    "publishedAt": "2026-04-15T16:21:29.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/IMG_8358-1024x681.jpg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/IMG_8358-1024x681.jpg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/IMG_8384-1024x643.jpg"
  },
  {
    "id": "https://agencia.ac.gov.br/projeto-escolar-transforma-alunos-em-produtores-de-documentario-sobre-a-historia-do-acre/",
    "slug": "projeto-escolar-transforma-alunos-em-produtores-de-documentario-sobre-a-historia-do-acre",
    "title": "Projeto escolar transforma alunos em produtores de documentário sobre a história do Acre",
    "summary": "Um projeto desenvolvido por alunos do 2º ano do ensino médio da Escola José Rodrigues Leite chama atenção pela criatividade e profundidade ao abordar a história do Acre. Com o nome “Sangue Acreano”, a atividade foi proposta na disciplina de Ciências Humanas durante as trilhas formativas e resultou na produção de conteúdos diversos, entre eles, [&#8230;] The post Projeto escolar transforma alunos em produtores de documentário sobre a história do Acre appeared first on Noticias do Acre .",
    "lede": "Um projeto desenvolvido por alunos do 2º ano do ensino médio da Escola José Rodrigues Leite chama atenção pela criatividade e profundidade ao abordar a história do Acre. Com o nome “Sangue Acreano”, a atividade foi proposta na disciplina de Ciências Humanas durante as trilhas formativas e resultou na produção de conteúdos diversos, entre eles, [&#8230;] The post Projeto escolar transforma alunos em produtores de documentário sobre a história do Acre appeared first on Noticias do Acre .",
    "url": "https://agencia.ac.gov.br/projeto-escolar-transforma-alunos-em-produtores-de-documentario-sobre-a-historia-do-acre/",
    "sourceUrl": "https://agencia.ac.gov.br/projeto-escolar-transforma-alunos-em-produtores-de-documentario-sobre-a-historia-do-acre/",
    "sourceName": "Agencia Acre",
    "sourceLabel": "Projeto escolar transforma alunos em produtores de documentário sobre a história do Acre",
    "category": "Educação",
    "publishedAt": "2026-04-15T15:51:10.000Z",
    "imageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-14-at-12.49.05-1024x681.jpeg",
    "feedImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/WhatsApp-Image-2026-04-14-at-12.49.05-1024x681.jpeg",
    "sourceImageUrl": "https://agencia.ac.gov.br/wp-content/uploads/2026/04/a3490024-b5f7-423a-81d4-396943a49c38-1024x683.jpg"
  }
];
