// @vitest-environment jsdom
import { beforeEach, expect, it, vi } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { createApp } from '../src/app.js';
const rootDir=process.cwd();
beforeEach(()=>{document.body.innerHTML='<div id="app"></div>'});
it('mostra login sem sessão e links dos dois APKs versionados',async()=>{await createApp({root:document.querySelector('#app'),apiClient:vi.fn().mockRejectedValue(new Error('401'))});expect(document.querySelector('[data-view=login]')).not.toBeNull();expect([...document.querySelectorAll('.app-downloads a')].map(a=>a.href)).toHaveLength(2);expect(document.querySelector('[name=identifier]').value).toBe('admin')});
it('registra o service worker',async()=>{const register=vi.fn().mockResolvedValue({});Object.defineProperty(navigator,'serviceWorker',{configurable:true,value:{register}});await createApp({root:document.querySelector('#app'),apiClient:vi.fn().mockRejectedValue(new Error('401'))});expect(register).toHaveBeenCalledWith('./sw.js',{scope:'./'})});
it('aplica a identidade azul e branca e mantém manifest instalável',()=>{const manifest=JSON.parse(readFileSync(`${rootDir}/manifest.webmanifest`,'utf8'));const html=readFileSync(`${rootDir}/index.html`,'utf8');expect(manifest.name).toBe('Angel Mídia Play');expect(manifest.theme_color).toBe('#f5f8ff');expect(html).toContain('assets/angel-midia-logo.png');expect(existsSync(`${rootDir}/assets/angel-midia-logo.png`)).toBe(true);expect(html).toContain('data-download="admin"');expect(html).toContain('data-download="tv"');for(const icon of manifest.icons)expect(existsSync(`${rootDir}/${icon.src}`)).toBe(true)});
it('não armazena respostas privadas da API no cache',()=>{const worker=readFileSync(`${rootDir}/sw.js`,'utf8');expect(worker).toContain("request.url.includes('/api/')");expect(worker).toContain('caches.open')});
it('usa o sistema visual Angel azul e branco e protege o layout responsivo',()=>{const css=readFileSync(`${rootDir}/src/styles.css`,'utf8')+readFileSync(`${rootDir}/src/responsive.css`,'utf8');expect(css).toContain('--angel-blue:#0f5eea');expect(css).toContain('--angel-surface:#ffffff');expect(css).toContain('min-width:0');expect(css).toContain('overflow-x:clip');expect(css).toContain('@media (prefers-reduced-motion:reduce)');expect(css).toContain('.sidebar{width:');expect(css).toContain('.operations-ribbon');expect(css).toContain('.company-photo-input')});
it('renderiza a central de operações aprovada sem os cards antigos',async()=>{const apiClient=vi.fn(async path=>path==='/auth/me'?{name:'Admin'}:[]);await createApp({root:document.querySelector('#app'),apiClient});expect(document.querySelector('.operations-ribbon')).not.toBeNull();expect(document.querySelector('[data-network-map]')).not.toBeNull();expect(document.querySelector('[data-tv-inventory]')).not.toBeNull();expect(document.querySelector('[data-company-gallery]')).not.toBeNull();expect(document.querySelector('[data-publish-network]')).not.toBeNull();expect(document.querySelectorAll('[data-map-device]')).toHaveLength(3);expect(document.querySelector('.action-card')).toBeNull();expect(document.body.textContent).toContain('Dados de demonstração local')});
it('oferece central de ajuda dentro do Admin',async()=>{const apiClient=vi.fn(async path=>path==='/auth/me'?{name:'Admin'}:[]);await createApp({root:document.querySelector('#app'),apiClient});const help=[...document.querySelectorAll('[data-nav]')].find(button=>button.textContent.includes('Ajuda'));expect(help).toBeTruthy();help.click();expect(document.querySelector('[data-view=help]')).not.toBeNull();expect(document.body.textContent).toContain('Primeiros passos');expect(document.body.textContent).toContain('Dúvidas frequentes')});
it('inclui o mapa real das TVs na visão inicial',()=>{const source=readFileSync(`${rootDir}/src/app.js`,'utf8')+readFileSync(`${rootDir}/src/overview.js`,'utf8');expect(source).toContain('Mapa da rede');expect(source).toContain('data-network-map');expect(source).toContain('renderDeviceMap');expect(source).toContain('LOCAL_DEMO_DEVICES')});
