// @vitest-environment jsdom
import { beforeEach, expect, it, vi } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { createApp } from '../src/app.js';
const rootDir=process.cwd();
beforeEach(()=>{document.body.innerHTML='<div id="app"></div>'});
it('mostra login sem sessão e links dos dois APKs versionados',async()=>{await createApp({root:document.querySelector('#app'),apiClient:vi.fn().mockRejectedValue(new Error('401'))});expect(document.querySelector('[data-view=login]')).not.toBeNull();expect([...document.querySelectorAll('.app-downloads a')].map(a=>a.href)).toHaveLength(2);expect(document.querySelector('[name=identifier]').value).toBe('admin')});
it('registra o service worker',async()=>{const register=vi.fn().mockResolvedValue({});Object.defineProperty(navigator,'serviceWorker',{configurable:true,value:{register}});await createApp({root:document.querySelector('#app'),apiClient:vi.fn().mockRejectedValue(new Error('401'))});expect(register).toHaveBeenCalledWith('./sw.js',{scope:'./'})});
it('aplica a identidade oficial e mantém manifest instalável',()=>{const manifest=JSON.parse(readFileSync(`${rootDir}/manifest.webmanifest`,'utf8'));const html=readFileSync(`${rootDir}/index.html`,'utf8');expect(manifest.name).toBe('Angel Mídia Play');expect(manifest.theme_color).toBe('#080e35');expect(html).toContain('assets/angel-midia-logo.png');expect(existsSync(`${rootDir}/assets/angel-midia-logo.png`)).toBe(true);expect(html).toContain('data-download="admin"');expect(html).toContain('data-download="tv"');for(const icon of manifest.icons)expect(existsSync(`${rootDir}/${icon.src}`)).toBe(true)});
it('não armazena respostas privadas da API no cache',()=>{const worker=readFileSync(`${rootDir}/sw.js`,'utf8');expect(worker).toContain("request.url.includes('/api/')");expect(worker).toContain('caches.open')});
it('usa o sistema visual Angel e protege o layout responsivo',()=>{const css=readFileSync(`${rootDir}/src/styles.css`,'utf8')+readFileSync(`${rootDir}/src/responsive.css`,'utf8');expect(css).toContain('--angel-navy:#080e35');expect(css).toContain('--angel-red:#e3062c');expect(css).toContain('min-width:0');expect(css).toContain('overflow-x:clip');expect(css).toContain('@media (prefers-reduced-motion:reduce)');expect(css).toContain('.brand-logo{width:');expect(css).toContain('.brand-masthead{min-height:');expect(css).toContain('.upload-card input:not([type=file])')});
it('mantém a interface administrativa aprovada com cards de ação',async()=>{const apiClient=vi.fn(async path=>path==='/auth/me'?{name:'Admin'}:[]);await createApp({root:document.querySelector('#app'),apiClient});expect(document.querySelectorAll('.action-card')).toHaveLength(4);expect(document.querySelector('.dashboard-guide')).not.toBeNull();expect(document.body.textContent).toMatch(/O que você quer\s*colocar no ar\?/)});
it('oferece central de ajuda dentro do Admin',async()=>{const apiClient=vi.fn(async path=>path==='/auth/me'?{name:'Admin'}:[]);await createApp({root:document.querySelector('#app'),apiClient});const help=[...document.querySelectorAll('[data-nav]')].find(button=>button.textContent.includes('Ajuda'));expect(help).toBeTruthy();help.click();expect(document.querySelector('[data-view=help]')).not.toBeNull();expect(document.body.textContent).toContain('Primeiros passos');expect(document.body.textContent).toContain('Dúvidas frequentes')});
it('inclui o mapa geral das TVs na visão inicial',()=>{const source=readFileSync(`${rootDir}/src/app.js`,'utf8');expect(source).toContain('Mapa geral das TVs');expect(source).toContain('data-overview-map');expect(source).toContain('renderDeviceMap')});
