"use strict";
const assert = require("node:assert/strict");
const { Readable } = require("node:stream");
const test = require("node:test");
const { createGarraAdminServerIntegration } = require("../server-integration");

function harness(){let state=null,id=0;const integration=createGarraAdminServerIntegration({rootDir:"C:/app",dataDir:"C:/data",readJson:(_p,f)=>state??f,writeJson:(_p,v)=>{state=structuredClone(v)},sendFile:(_q,res,file,options)=>{res.file=file;res.options=options},isAdmin:req=>req.headers.authorization==="ok",getActor:()=>"admin:test",now:()=>new Date("2026-08-27T15:00:00Z"),idFactory:()=>`id-${++id}`});return integration}
function req(method,url,headers={},body=""){const request=Readable.from(body?[body]:[]);request.method=method;request.url=url;request.headers={host:"local",...headers};return request}
function res(){return{status:null,headers:null,body:"",writeHead(status,headers){this.status=status;this.headers=headers},end(chunk=""){this.body+=chunk}}}

test("blocks API and static UI without admin authentication",async()=>{const app=harness();let response=res();assert.equal(await app.handleApi(req("GET","/api/garra-admin/summary"),response,"/api/garra-admin/summary"),true);assert.equal(response.status,401);response=res();assert.equal(await app.handleStatic(req("GET","/garra-admin/"),response,"/garra-admin/"),true);assert.equal(response.status,401);assert.match(response.body,/administrativo/i)});
test("returns homologation summary and no-store headers",async()=>{const app=harness(),response=res();await app.handleApi(req("GET","/api/garra-admin/summary",{authorization:"ok"}),response,"/api/garra-admin/summary");assert.equal(response.status,200);assert.equal(response.headers["Cache-Control"],"no-store");assert.equal(JSON.parse(response.body).mode,"homologation")});
test("requires idempotency and replays a protected inventory command",async()=>{const app=harness();const payload=JSON.stringify({name:"Urso Céu",rarity:"rare",quantity:2,unitCostCents:2500,reason:"teste"});let response=res();await app.handleApi(req("POST","/api/garra-admin/inventory/batches",{authorization:"ok"},payload),response,"/api/garra-admin/inventory/batches");assert.equal(response.status,400);response=res();await app.handleApi(req("POST","/api/garra-admin/inventory/batches",{authorization:"ok","idempotency-key":"same"},payload),response,"/api/garra-admin/inventory/batches");assert.equal(response.status,201);response=res();await app.handleApi(req("POST","/api/garra-admin/inventory/batches",{authorization:"ok","idempotency-key":"same"},payload),response,"/api/garra-admin/inventory/batches");assert.equal(response.status,200);assert.equal(JSON.parse(response.body).replayed,true)});
test("serves only the protected admin public root",async()=>{const app=harness(),response=res();await app.handleStatic(req("GET","/garra-admin/garra-admin.css",{authorization:"ok"}),response,"/garra-admin/garra-admin.css");assert.match(response.file,/garra-admin[\\/]public[\\/]garra-admin\.css$/);assert.equal(response.options.cacheControl,"no-store");assert.equal(await app.handleStatic(req("GET","/other",{authorization:"ok"}),res(),"/other"),false)});
