import { randomUUID } from 'node:crypto';
import { requireAdmin } from '../auth.js';
import { validateAdvertiser,validateMonth,validateMediaLinks,summarizeFinancial } from '../services/advertisers.js';

export default async function advertiserRoutes(app){
  app.get('/api/admin/advertisers',{preHandler:requireAdmin},async()=>{const {rows}=await app.db.query(`select a.*,coalesce(json_agg(json_build_object('id',ma.asset_id,'name',m.display_name,'type',m.content_type)) filter(where ma.asset_id is not null),'[]') as media from advertisers a left join media_advertisers ma on ma.advertiser_id=a.id left join media_assets m on m.id=ma.asset_id group by a.id order by a.name`);return{advertisers:rows};});
  app.post('/api/admin/advertisers',{preHandler:requireAdmin},async(req,reply)=>{const p=validateAdvertiser(req.body);if(!p.ok)return reply.code(400).send({error:'invalid_request'});const id=randomUUID(),v=p.value;await app.db.query('insert into advertisers(id,name,contact_name,phone,email,notes) values($1,$2,$3,$4,$5,$6)',[id,v.name,v.contactName,v.phone,v.email,v.notes]);return reply.code(201).send({id});});
  app.put('/api/admin/advertisers/:id/media',{preHandler:requireAdmin},async(req,reply)=>{const p=validateMediaLinks(req.body);if(!p.ok)return reply.code(400).send({error:'invalid_request'});await app.db.query('delete from media_advertisers where advertiser_id=$1',[req.params.id]);for(const assetId of p.value)await app.db.query('insert into media_advertisers(advertiser_id,asset_id) values($1,$2)',[req.params.id,assetId]);return reply.code(204).send();});
  app.post('/api/admin/advertisers/:id/months',{preHandler:requireAdmin},async(req,reply)=>{const p=validateMonth(req.body);if(!p.ok)return reply.code(400).send({error:'invalid_request'});const v=p.value;await app.db.query(`insert into advertiser_months(id,advertiser_id,competence,monthly_amount_cents,status,notes) values($1,$2,$3,$4,$5,$6) on conflict(advertiser_id,competence) do update set monthly_amount_cents=excluded.monthly_amount_cents,status=excluded.status,notes=excluded.notes,updated_at=now()`,[randomUUID(),req.params.id,v.competence,v.amountCents,v.status,v.notes]);return reply.code(204).send();});
  app.get('/api/admin/financial-report',{preHandler:requireAdmin},async(req)=>{const competence=/^\d{4}-\d{2}$/.test(req.query?.competence??'')?req.query.competence:new Date().toISOString().slice(0,7);const {rows}=await app.db.query(`select a.id advertiser_id,a.name advertiser_name,coalesce(am.monthly_amount_cents,0) monthly_amount_cents,coalesce(am.status,'pending') payment_status,count(pe.id) filter(where pe.event_type='completed') displays,count(distinct pe.device_id) filter(where pe.event_type='completed') tvs,count(distinct pe.asset_id) filter(where pe.event_type='completed') media_count from advertisers a left join advertiser_months am on am.advertiser_id=a.id and am.competence=$1::date left join playback_events pe on pe.advertiser_id=a.id and pe.occurred_at >= $1::date and pe.occurred_at < ($1::date+interval '1 month') group by a.id,a.name,am.monthly_amount_cents,am.status order by displays desc,a.name`,[`${competence}-01`]);return{competence,...summarizeFinancial(rows)};});
}
