import { randomUUID } from 'node:crypto';
import { requireAdmin } from '../auth.js';
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export function validateEmergency(b){if(!b||!['message','media'].includes(b.mode))return{ok:false};const title=typeof b.title==='string'?b.title.trim().slice(0,160):'',message=typeof b.message==='string'?b.message.trim().slice(0,1000):'',assetId=b.assetId??null;if(b.mode==='message'&&!title&&!message)return{ok:false};if(b.mode==='media'&&!UUID.test(assetId??''))return{ok:false};return{ok:true,value:{mode:b.mode,title,message,assetId:b.mode==='media'?assetId:null}};}
export default async function emergencyRoutes(app){
  app.get('/api/admin/emergency',{preHandler:requireAdmin},async()=>{const {rows}=await app.db.query(`select e.*,m.display_name media_name,m.content_type from emergency_broadcasts e left join media_assets m on m.id=e.asset_id where e.active order by e.activated_at desc limit 1`);return{active:!!rows[0],broadcast:rows[0]??null};});
  app.post('/api/admin/emergency',{preHandler:requireAdmin},async(req,reply)=>{const p=validateEmergency(req.body);if(!p.ok)return reply.code(400).send({error:'invalid_request'});await app.db.query('update emergency_broadcasts set active=false,ended_at=now(),ended_by=$1 where active',[req.admin.id]);const id=randomUUID(),v=p.value;await app.db.query('insert into emergency_broadcasts(id,mode,title,message,asset_id,activated_by) values($1,$2,$3,$4,$5,$6)',[id,v.mode,v.title,v.message,v.assetId,req.admin.id]);await app.db.query('update devices set schedule_version=schedule_version+1,updated_at=now()');return reply.code(201).send({id,active:true});});
  app.delete('/api/admin/emergency',{preHandler:requireAdmin},async(req,reply)=>{await app.db.query('update emergency_broadcasts set active=false,ended_at=now(),ended_by=$1 where active',[req.admin.id]);await app.db.query('update devices set schedule_version=schedule_version+1,updated_at=now()');return reply.code(204).send();});
}
